<?php

return array (
  'name' => '星核',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.5',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' =>
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' =>
  array (
    'default' => '默认',
    'page' => '单页',
    'article' => '文章',
    'test' => 'Test',
  ),
  'configgroup' =>
  array (
    'basic' => '基础配置',
    'dictionary' => '字典配置',
    'contents' => '文本协议',
    'follow' => '关注我们',
    'contact' => '联系我们',
    'goods' => 'NFT设置',
    'compose' => '竞价配置',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '1129205956@qq.com',
  'mail_smtp_pass' => 'dpauixlvnlwqicff',
  'mail_verify_type' => '2',
  'mail_from' => '1129205956@qq.com',
  'attachmentcategory' =>
  array (
    'category1' => '分类一',
    'category2' => '分类二',
    'custom' => '自定义',
  ),
  'default_image' =>
  array (
    0 => '/uploads/20220530/205d9d61a87d3172d918bec549d0cc15.png',
  ),
  'users_content' => '<div><span style="font-size: 18px;">一、注册协议条款的确认和接受</span></div><div><span style="font-size: 18px;">“</span><span style="font-size: 18px;">星核</span><span style="font-size: 18px;">”APP（以下亦称“本应用”），隶属于河南省神肆文化传媒</span><span style="font-size: 18px;">科技有限公司</span><span style="font-size: 18px;">。同意按照本协议的规定及其不定时发布的操作规则提供基于互联网和移动互联网的相关服务（以下称“网络服务”）。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">为获得网络服务，申请人应当认真阅读、充分理解本《协议》中各条款，包括免除或者限制本应用责任的免责条款及对用户的权利限制条款。审慎阅读并选择接受或不接受本《协议》（未成年人应在法定监护人陪同下阅读）。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">同意接受本协议的全部条款的，申请人应当按照页面上的提示完成全部的注册程序，并在注册程序过程中点击“同意”按钮，否则视为不接受本《协议》全部条款，申请人应当终止并退出申请。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">本《协议》可由本应用定期更新，更新后的协议条款一旦公布即代替原来的协议条款，恕不再另行通知，用户可在本应用查阅最新版协议条款。在本应用修改《协议》条款后，如果用户不接受修改后的条款，请立即停止使用本应用提供的网络服务，继续使用的用户将被视为已接受了修改后的协议。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">二、服务内容</span></div><div><span style="font-size: 18px;">1、网络服务的具体内容由本应用根据实际情况提供，包括资讯、工具、社群。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">2、本应用提供的网络服务包括收费和免费。对于收费服务，本应用会在用户使用之前给予用户明确的提示，只有用户根据提示确认同意支付相关费用，用户才能使用该等收费服务。如用户未支付相关费用，则本应用有权不向用户提供该等收费服务。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">3、用户理解，本应用仅提供本应用明确承诺的网络服务，除此之外与相关网络服务有关的设备（如个人电脑、手机、及其他与接入互联网或移动网有关的装置）及所需的费用（如为接入互联网而支付的电话费及上网费、为使用移动网络而支付的手机费）均应由用户自行负担。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">三、用户帐号</span></div><div><span style="font-size: 18px;">1、经本应用注册系统完成注册程序并通过身份认证的用户即为正式用户。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">2、如发现用户帐号中含有不雅文字或不恰当名称的，本应用保留注销其用户帐号的权利。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">3、用户帐号的所有权归本应用，用户完成申请注册手续后，用户享有使用权。3个月未使用的用户账号，本应用保留收回的权利。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">4、用户有义务保证密码和帐号的安全，用户利用该帐号所进行的一切活动引起的任何损失或损害，由用户自行承担全部责任，本应用不承担任何责任。如用户发现帐号遭到未授权的使用或发生其他任何安全问题，应立即修改账号密码并妥善保管。因黑客行为或用户的保管疏忽导致帐号非法使用，本应用不承担任何责任。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">5、用户帐号和密码仅由初始申请注册人使用，用户不得将自己用户账户或密码有偿或无偿以转让、出借、授权等方式提供给第三人操作和使用，否则用户应当自行承担因违反此要求而遭致的任何损失。违反本项约定的，本应用并保留收回账号的权利。若因违反本约定对他人造成损害的，用户应与实际使用人承担连带赔偿责任，同时本应用保留追究用户违约责任的权利。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">6、用户帐号在丢失、遗忘密码及因合用产生使用权归属纠纷后，须遵照本应用的申诉途径请求找回帐号。用户可以凭初始注册资料向本应用申请找回帐号。本应用的账户恢复机制仅负责识别申请用户所提资料与系统记录资料是否一致，而无法识别申诉人是否系帐号的真正使用权人。对用户因被他人冒名申请而致的任何损失，本应用不承担任何责任，用户知晓帐号及密码保管责任在于用户，本应用并不承诺帐号丢失或遗忘密码后用户一定能通过申诉找回帐号。用户应当谨慎填写初始手机号或注册邮箱作为确认接收争议帐号的指定邮箱。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">7、本应用建议用户应当使用本人名义为用户账户充值或行使付款行为。若用户存在使用第三人的名义进行充值或付款，或委托第三人代为充值或付款之行为的，则以上行为被视作本人的行为，若由于该第三人行为导致充值或付款行为失败或成功后又被撤销的，均被认为是用户本人真实意思的表示和用户本人实施的行为，由此所造成的一切法律后果均由用户自行承担。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">四、使用规则</span></div><div><span style="font-size: 18px;">1、用户在使用本应用网络服务过程中，必须遵循国家的相关法律法规，不得发布危害国家安全、色情、暴力、侵犯版权等任何合法权利等非法内容;也不得利用本应用平台发布含有虚假、有害、胁迫、侵害他人隐私、骚扰、侵害、中伤、粗俗、或其它道德上令人反感的内容。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">2、本应用可依其合理判断，对违反有关法律法规或本协议约定;或侵犯、妨害、威胁任何人权利或安全的内容，或者假冒他人的行为，本应用有权停止传输任何前述内容，并有权依其自行判断对违反本条款的任何用户采取适当的法律行动，包括但不限于，隐匿和下架具有违法性、侵权性、不当性等内容，阻止其使用本应用全部或部分网络服务，并且依据法律法规保存有关信息并向有关部门报告等。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">3、对于经由本应用网络服务而传送的内容，本应用不保证前述内容的正确性、完整性或品质。用户在接受本服务时，有可能会接触到令人不快、不适当或令人厌恶的内容。在任何情况下，本应用均不对任何内容负责，包括但不限于任何内容发生任何错误或纰漏以及衍生的任何损失或损害。本应用有权（但无义务）自行拒绝或删除经由本应用网络服务提供的任何内容。用户使用上述内容，应自行承担风险。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">4、用户通过本应用网络服务所发布的任何内容并不反映本应用的观点或政策，本应用对此不承担任何责任。用户须对上述内容的真实性、合法性、无害性、有效性等全权负责，与用户所发布信息相关的任何法律责任由用户自行承担，与本应用无关。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">五、版权声明</span></div><div><span style="font-size: 18px;">本应用中包含的任何文本、图片、图形、音频和/或视频资料均受版权、商标和/或其它财产所有权法律的保护，未经相关权利人同意，上述资料均不得在任何媒体直接或间接发布、播放、出于播放或发布目的而改写或再发行，或者被用于其他任何商业目的。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">六、隐私保护</span></div><div><span style="font-size: 18px;">1、保护用户隐私是本应用的一项基本政策，本应用保证不对外公开或向第三方提供用户的注册资料及用户在使用网络服务时存储在本应用内的非公开内容，但下列情况除外:</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（1）事先获得用户的书面明确授权</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（2）根据有关的法律法规要求</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（3）按照相关政府主管部门的要求</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（4）为维护社会公众的利益</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（5）为维护本应用的合法权益</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">2、为了更好地为用户提供全面服务，用户同意本应用可将用户注册资料及使用信息提供本应用关联公司使用。本应用保证前述关联公司同等级地严格遵循本协议第六条第1款之隐私保护责任。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">3、用户同意：本应用或本应用运营商的关联公司在必要时有权根据用户注册时或接受服务时所提供的联系信息（包括但不限于电子邮件地址、联系电话、联系地址、即时聊天工具账号等），通过电子邮件、电话、短信、邮寄、即时聊天、弹出页面等方式向用户发送如下信息：</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（1）各类重要通知信息，可能包括但不限于订单、交易单、修改密码提示等重要信息。此类信息可能对用户的权利义务产生重大的有利或不利影响，用户务必及时关注。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（2）商品和服务广告、促销优惠等商业性信息。若用户不愿意接收此类信息，则可通过告知（口头或书面）的方式通知本应用或本应用运营商的关联公司取消发送，亦可通过本应用或本应用运营商关联公司所提供的相应退订功能（若有）进行退订。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">七、协议的用途、更新和效力</span></div><div><span style="font-size: 18px;">1、本协议之服务条款用以规范用户使用本应用提供的服务，本协议与本应用社区行为准则构成完整的协议。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">2、鉴于国家法律法规不时变化及本应用运营之需要，本应用有权对本协议条款不时地进行修改，修改后的协议一旦被公布于本应用上即告生效，并替代原来的协议。用户有义务不时关注并阅读最新版的协议及网站公告。如用户不同意更新后的协议，则应立即停止接受本应用依据本协议提供的服务；若用户继续使用本应用提供的服务的，即视为同意更新后的协议。如果本协议中任何一条被视为废止、无效或因任何理由不可执行，该条应视为可分的且并不影响任何其余条款的有效性和可执行性。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">八、联系方式</span></div><div><span style="font-size: 18px;">当你有个人信息相关问题或其他的投诉、建议等，可以通过如下方式与本应用联系，本应用将尽快审核所涉及内容，并于15个工作日内对于你的问题、投诉、建议进行回复；</span></div><div><span style="font-size: 18px;"><br></span></div><div><br></div><div><br></div>',
  'share_image' => '/uploads/20220423/57ebc1489570480f170e64740abcd5a4.png',
  'register_url' => 'http://app.xh8896.com/h5',
  'award_rate' => '6',
  'level_rate' => '1',
  'first_rate' => '3',
  'second_rate' => '2',
  'ali_app_id' => '2021002140681692',
  'ali_public_key' => 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo+E9TxUPz5wtG1xzHcgFNT+2qzaDTzozBnJf/zB/AloLWZQOceB4HDKu9wqvZDWZr48BB1prEVOox5YnGt/3SmTsjcvsXUpnXCZVxnGAL2Zw2zY6C+kfOU5ctNr254MAnNSA6QxlZPmaeTTgd4W/iQTyHWKSZpQE6f2OEJDWAOQyn+7mls5FBmMWxtxAX5ybpf5VaanjGFGRwv+eSH1So4C9hIhV195iMxnAesjMptd83kgPRwYz/fhyBlAsfHOu7xA0iwriIwA8MvUuVTJcKAI+TLMfFuda//QyAXzMwSHZ8IXqZfaHfRttZg9eGxy07qOV6zvrtaCd1VhHAx060wIDAQAB',
  'ali_private_key' => 'MIIEpQIBAAKCAQEAtzf8tsvG8cy7eiljjeRHOFGJjZl0RFywGv5BRGqkJcJ0XBdd0NwSSkRgYKfZhe3uxstRznQVyC3f5YP4TDcGH86zltIGFZle81AJdwVTPkT5x2KERKcSwI+wG3SJolUtEUStOj4z+TABn+Hmpg49PFT6RSZyyJZ47PUdXGUzX5sjUzdSy50IalMGw1+TsrHgiQKHUdptHey7Kiavt7OobRVfzfC9zyMRctAhrptZ96riYuV8gisB3Hjya+YDTYrAljgjI7i1bDnViVfrjukyKTsFia9jO8nW6R2YvIj7BxHGkZAFTppaq3hW+Yv+aV/mk+G2xffMvFcrrZqGWbNEKQIDAQABAoIBAQCW/YvFNTAxqvBBn4RMtfi/f+qlB/aaM+xpgmlVMbEu8Q6lqhgFfKeSDsGCRjFsPwYNTBeR1Xbx7mRaqCRi4uGoKtczjse22xs11xrFvFy6r2tNFnI8hZddm8ydA7A9WIZ4ealsm0CHtjlQgoFrDccHRlytyh7EEcV8OhBFSZ1JxpH4KErVLw7Cm34NoGFG7PFtKFzDYMbJvHqXt5MsfmEhwYZC6mxRYitT2wHSIB6XcBykm4IoUsj/uVHiTTA8kvJLx11sU/xjGuSNNVglkjbFaXaTz/miTDPaBVrJokKtfBy6Dc+FBRit01Azsa+bQg3qYYQoczSmvnMhAdUsnfelAoGBAN9OEk9Ho6hks3X/bekxbWMCirQL0+0kCkaD9jMJ0sOYnEaqAo4L1x/M9rkQM2AjXFPIZt2PbH2zIZFQpnM98J2Ad72Iq/OTYCSmKrfcmmah+4//iEJHtXt6EMHxazA7Wkt8VBk+UgQRiVBFHLliQi+oSIcJmX58gdd0F9zVu+RTAoGBANILZmucsFGIlQteUAssv5lypYc8icbcEaxp7MSTD90i6oZv0Yq81+DNTFvW2FQKy0PHq50WEkKbBdXHAnF5pLZmMeJz4ux7hPdKF0OGC19SXi3GhxitGrGa45Qj6hUja8hkCIAbd0eJwZucP0kjOcAh+Rn/oZzLmYo0rjnoDyYTAoGBAKHIVVmc5IQm2SI/Oek+Bys5dzY0b4kamFs4VhHqJwnQskA8AffZujTu8T1o8F/Rnp2Qzn3s4EQ9mK9ISB+sG3xwy8/EihfBiWFkBgUJTc/XwYM1NgoXG/Pmnud0Oh1KkwOnguJ7FT6fWeWO/N2Ow7b1a/5xxQQvvn5TPMqhCyzDAoGAdx6N/DOFbwfldugKvvumwXBaXaLAhC2kPEJqS2UXlxLJLGrXzDWivFPRnTfvwWHJuuvO8KxmuK1QFtfhE9enyOWWHtYX+INoehHjtaCcbHe6/3zaeu0Y+WZc8FOZ2lkXNDM++uAYulJuoUBwR5sZklPyAIOP9OsmbVHJCQAJL08CgYEAsaiGTzjiehR/vGRov+FFMkiZJYQZDInzAdwMz+ofqu4+4Zbb0yh4wJDyHTpMfk8r9XzKSe3ACFoHnAVy/3RHMwY0/AlxTeFUQqp6we53oUH6JYTKPDe8Dqx7oZZGUP7KVn23A/SDU9ck3uXIbJxASMpCsOol7GGal1uDfVJ3e3s=',
  'wx_app_id' => '',
  'wx_app_secret' => '',
  'wx_mch_id' => '',
  'wx_mch_key' => '',
  'is_appoint' => '1',
  'shop_award_rate' => '2',
  'register_award_number' => '10',
  'total_award_number' => '10',
  'sales_order_number' => '1',
  'appoint_account' => '500',
  'rush_rule' => '1',
  'register_day' => '10',
  'register_premium_min_number' => '1',
  'register_premium_max_number' => '9',
  'premium_max_number' => '10',
  'sales_wholesale_rate' => '90',
  'sales_e_rate' => '10',
  'split_rule' => '2',
  'thirty_un_pay' => '50',
  'sixty_un_pay' => '100',
  'thirty_un_confirm' => '50',
  'gift_account' => '5000',
  'pay_time' => '60',
  'confirm_time' => '30',
  'server_url' => 'http://app.xh8896.com/h5',
  'ali_notify_url' => 'http://app.xh8896.com/api/notify/aliNotify',
  'wx_small_app_id' => '',
  'wx_small_app_secret' => '',
  'wx_notify_url' => 'http://app.xh8896.com/api/notify/wxNotify',
  'conceal_content' => '<div><span style="font-size: 18px;">一、注册协议条款的确认和接受</span></div><div><span style="font-size: 18px;">“</span><span style="font-size: 18px;">星核</span><span style="font-size: 18px;">”APP（以下亦称“本应用”），隶属于</span><span style="font-size: 18px;">河南省神肆文化传媒</span><span style="font-size: 18px;">科技有限公司</span><span style="font-size: 18px;">。同意按照本协议的规定及其不定时发布的操作规则提供基于互联网和移动互联网的相关服务（以下称“网络服务”）。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">为获得网络服务，申请人应当认真阅读、充分理解本《协议》中各条款，包括免除或者限制本应用责任的免责条款及对用户的权利限制条款。审慎阅读并选择接受或不接受本《协议》（未成年人应在法定监护人陪同下阅读）。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">同意接受本协议的全部条款的，申请人应当按照页面上的提示完成全部的注册程序，并在注册程序过程中点击“同意”按钮，否则视为不接受本《协议》全部条款，申请人应当终止并退出申请。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">本《协议》可由本应用定期更新，更新后的协议条款一旦公布即代替原来的协议条款，恕不再另行通知，用户可在本应用查阅最新版协议条款。在本应用修改《协议》条款后，如果用户不接受修改后的条款，请立即停止使用本应用提供的网络服务，继续使用的用户将被视为已接受了修改后的协议。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">二、服务内容</span></div><div><span style="font-size: 18px;">1、网络服务的具体内容由本应用根据实际情况提供，包括资讯、工具、社群。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">2、本应用提供的网络服务包括收费和免费。对于收费服务，本应用会在用户使用之前给予用户明确的提示，只有用户根据提示确认同意支付相关费用，用户才能使用该等收费服务。如用户未支付相关费用，则本应用有权不向用户提供该等收费服务。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">3、用户理解，本应用仅提供本应用明确承诺的网络服务，除此之外与相关网络服务有关的设备（如个人电脑、手机、及其他与接入互联网或移动网有关的装置）及所需的费用（如为接入互联网而支付的电话费及上网费、为使用移动网络而支付的手机费）均应由用户自行负担。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">三、用户帐号</span></div><div><span style="font-size: 18px;">1、经本应用注册系统完成注册程序并通过身份认证的用户即为正式用户。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">2、如发现用户帐号中含有不雅文字或不恰当名称的，本应用保留注销其用户帐号的权利。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">3、用户帐号的所有权归本应用，用户完成申请注册手续后，用户享有使用权。3个月未使用的用户账号，本应用保留收回的权利。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">4、用户有义务保证密码和帐号的安全，用户利用该帐号所进行的一切活动引起的任何损失或损害，由用户自行承担全部责任，本应用不承担任何责任。如用户发现帐号遭到未授权的使用或发生其他任何安全问题，应立即修改账号密码并妥善保管。因黑客行为或用户的保管疏忽导致帐号非法使用，本应用不承担任何责任。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">5、用户帐号和密码仅由初始申请注册人使用，用户不得将自己用户账户或密码有偿或无偿以转让、出借、授权等方式提供给第三人操作和使用，否则用户应当自行承担因违反此要求而遭致的任何损失。违反本项约定的，本应用并保留收回账号的权利。若因违反本约定对他人造成损害的，用户应与实际使用人承担连带赔偿责任，同时本应用保留追究用户违约责任的权利。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">6、用户帐号在丢失、遗忘密码及因合用产生使用权归属纠纷后，须遵照本应用的申诉途径请求找回帐号。用户可以凭初始注册资料向本应用申请找回帐号。本应用的账户恢复机制仅负责识别申请用户所提资料与系统记录资料是否一致，而无法识别申诉人是否系帐号的真正使用权人。对用户因被他人冒名申请而致的任何损失，本应用不承担任何责任，用户知晓帐号及密码保管责任在于用户，本应用并不承诺帐号丢失或遗忘密码后用户一定能通过申诉找回帐号。用户应当谨慎填写初始手机号或注册邮箱作为确认接收争议帐号的指定邮箱。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">7、本应用建议用户应当使用本人名义为用户账户充值或行使付款行为。若用户存在使用第三人的名义进行充值或付款，或委托第三人代为充值或付款之行为的，则以上行为被视作本人的行为，若由于该第三人行为导致充值或付款行为失败或成功后又被撤销的，均被认为是用户本人真实意思的表示和用户本人实施的行为，由此所造成的一切法律后果均由用户自行承担。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">四、使用规则</span></div><div><span style="font-size: 18px;">1、用户在使用本应用网络服务过程中，必须遵循国家的相关法律法规，不得发布危害国家安全、色情、暴力、侵犯版权等任何合法权利等非法内容;也不得利用本应用平台发布含有虚假、有害、胁迫、侵害他人隐私、骚扰、侵害、中伤、粗俗、或其它道德上令人反感的内容。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">2、本应用可依其合理判断，对违反有关法律法规或本协议约定;或侵犯、妨害、威胁任何人权利或安全的内容，或者假冒他人的行为，本应用有权停止传输任何前述内容，并有权依其自行判断对违反本条款的任何用户采取适当的法律行动，包括但不限于，隐匿和下架具有违法性、侵权性、不当性等内容，阻止其使用本应用全部或部分网络服务，并且依据法律法规保存有关信息并向有关部门报告等。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">3、对于经由本应用网络服务而传送的内容，本应用不保证前述内容的正确性、完整性或品质。用户在接受本服务时，有可能会接触到令人不快、不适当或令人厌恶的内容。在任何情况下，本应用均不对任何内容负责，包括但不限于任何内容发生任何错误或纰漏以及衍生的任何损失或损害。本应用有权（但无义务）自行拒绝或删除经由本应用网络服务提供的任何内容。用户使用上述内容，应自行承担风险。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">4、用户通过本应用网络服务所发布的任何内容并不反映本应用的观点或政策，本应用对此不承担任何责任。用户须对上述内容的真实性、合法性、无害性、有效性等全权负责，与用户所发布信息相关的任何法律责任由用户自行承担，与本应用无关。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">五、版权声明</span></div><div><span style="font-size: 18px;">本应用中包含的任何文本、图片、图形、音频和/或视频资料均受版权、商标和/或其它财产所有权法律的保护，未经相关权利人同意，上述资料均不得在任何媒体直接或间接发布、播放、出于播放或发布目的而改写或再发行，或者被用于其他任何商业目的。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">六、隐私保护</span></div><div><span style="font-size: 18px;">1、保护用户隐私是本应用的一项基本政策，本应用保证不对外公开或向第三方提供用户的注册资料及用户在使用网络服务时存储在本应用内的非公开内容，但下列情况除外:</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（1）事先获得用户的书面明确授权</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（2）根据有关的法律法规要求</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（3）按照相关政府主管部门的要求</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（4）为维护社会公众的利益</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（5）为维护本应用的合法权益</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">2、为了更好地为用户提供全面服务，用户同意本应用可将用户注册资料及使用信息提供本应用关联公司使用。本应用保证前述关联公司同等级地严格遵循本协议第六条第1款之隐私保护责任。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">3、用户同意：本应用或本应用运营商的关联公司在必要时有权根据用户注册时或接受服务时所提供的联系信息（包括但不限于电子邮件地址、联系电话、联系地址、即时聊天工具账号等），通过电子邮件、电话、短信、邮寄、即时聊天、弹出页面等方式向用户发送如下信息：</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（1）各类重要通知信息，可能包括但不限于订单、交易单、修改密码提示等重要信息。此类信息可能对用户的权利义务产生重大的有利或不利影响，用户务必及时关注。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">（2）商品和服务广告、促销优惠等商业性信息。若用户不愿意接收此类信息，则可通过告知（口头或书面）的方式通知本应用或本应用运营商的关联公司取消发送，亦可通过本应用或本应用运营商关联公司所提供的相应退订功能（若有）进行退订。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">七、协议的用途、更新和效力</span></div><div><span style="font-size: 18px;">1、本协议之服务条款用以规范用户使用本应用提供的服务，本协议与本应用社区行为准则构成完整的协议。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">2、鉴于国家法律法规不时变化及本应用运营之需要，本应用有权对本协议条款不时地进行修改，修改后的协议一旦被公布于本应用上即告生效，并替代原来的协议。用户有义务不时关注并阅读最新版的协议及网站公告。如用户不同意更新后的协议，则应立即停止接受本应用依据本协议提供的服务；若用户继续使用本应用提供的服务的，即视为同意更新后的协议。如果本协议中任何一条被视为废止、无效或因任何理由不可执行，该条应视为可分的且并不影响任何其余条款的有效性和可执行性。</span></div><div><span style="font-size: 18px;"><br></span></div><div><span style="font-size: 18px;">八、联系方式</span></div><div><span style="font-size: 18px;">当你有个人信息相关问题或其他的投诉、建议等，可以通过如下方式与本应用联系，本应用将尽快审核所涉及内容，并于15个工作日内对于你的问题、投诉、建议进行回复；</span></div><div><span style="font-size: 18px;"><br></span></div><div><br></div><div><br></div>',
  'wx_small_notify_url' => 'http://app.xh8896.com/api/notify/wxSmallNotify',
  'buy_content' => '<p><br></p>',
  'wx_image' => '/uploads/20220118/f0340570fa4c0a70cbc9e69ee5a1c6d9.png',
  'qq_iamge' => '/uploads/20220118/17928c3d43856f4dd216a14b4ef0b32e.png',
  'contact_phone_1' => '11111',
  'app_download' => '',
  '技术支持' => '',
  'zqh' => '/uploads/20220110/b07dd605a8f77a8c0fde431b48360219.png',
  'about_content' => '<p><br></p>',
  'douyi_image' => '/uploads/20220119/0fdf060dde128f30883787a795ee2b08.jpg',
  'is_trade' => '1',
  'trade_day' => '5',
  'bidding_rules' => '<p><b>竞价规则：</b></p><p>1、发售一款上古神兽合成碎片</p><p>2、各个合成材料对应合成各个产物</p><p><br></p><p><b>活动时间：</b></p><p>2022年4月25日 00:00:00 至&nbsp; 2022年4月30日 23:59:59</p>',
  'sub_commission' => '5',
  'blind_box_level_1' => '224',
  'blind_box_level_1_probability' => '1',
  'blind_box_level_2' => '227',
  'blind_box_level_2_part_1_probability' => '2',
  'blind_box_level_2_part_2_probability' => '2.5',
  'blind_box_level_2_part_3_probability' => '3',
  'blind_box_level_2_part_4_probability' => '3.5',
  'blind_box_level_3' => '3',
  'blind_box_level_3_part_1_probability' => '3.1',
  'blind_box_level_3_part_2_probability' => '3.2',
  'blind_box_level_3_part_3_probability' => '3.3',
  'blind_box_level_3_part_4_probability' => '3.3',
  'blind_box_level_4' => '2',
  'blind_box_level_4_part_1_probability' => '4.1',
  'blind_box_level_4_part_2_probability' => '4.2',
  'blind_box_level_4_part_3_probability' => '4.3',
  'blind_box_level_4_part_4_probability' => '4.4',
  'blind_box_level_5' => '1',
  'blind_box_level_5_part_1_probability' => '5.1',
  'blind_box_level_5_part_2_probability' => '5.2',
  'blind_box_level_5_part_3_probability' => '5.3',
  'blind_box_level_5_part_4_probability' => '5.4',
  'blind_box_level_6' => '231',
  'blind_box_level_6_part_1_probability' => '6.1',
  'blind_box_level_6_part_2_probability' => '6.2',
  'blind_box_level_6_part_3_probability' => '6.3',
  'blind_box_level_6_part_4_probability' => '6.4',
  'blind_box_level_7' => '225',
  'blind_box_level_7_part_1_probability' => '7.1',
  'blind_box_level_7_part_2_probability' => '7.2',
  'blind_box_level_7_part_3_probability' => '7.3',
  'blind_box_level_7_part_4_probability' => '7.4',
  'commission_level_1' => '3',
  'commission_level_2' => '2',
  'bidding_step' => '10',
  'transaction_fees' => '1',
);
